![](https://www.dii.uchile.cl/wp-content/uploads/2021/06/Magi%CC%81ster-en-Ciencia-de-Datos.png)

**MDS7202: Laboratorio de Programación Científica para Ciencia de Datos**

### 👨‍🏫👩‍🏫 Cuerpo Docente:

- Profesores: Diego Cortez, Gabriel Iturra
- Auxiliares: Melanie Peña, Valentina Rojas
- Ayudantes: Nicolás Cabello, Cristopher Urbina

### 👨‍💻👩‍💻 Estudiantes:
- Estudiante n°1: Josefa Anselmo 
- Estudiante n°2: Tamara Carrasco.

_Por favor, lean detalladamente las instrucciones de la tarea antes de empezar a escribir._

---

### **Instrucciones importantes**

1. **Formato del informe**:  
   - El informe debe estar integrado dentro de un **Jupyter Notebook**. No es necesario subirlo a una plataforma externa, pero debe cumplir con los siguientes requisitos:  
     - Estructura clara y ordenada.  
     - Código acompañado de explicaciones detalladas.  
     - Resultados presentados de forma visual y analítica.  

2. **Descuento por informes deficientes**:  
   - Cualquier sección del informe que no tenga una explicación adecuada o no respete el formato será penalizada con un descuento en la nota. Esto incluye código sin comentarios o análisis que no sean coherentes con los resultados presentados.
   - **Comentarios sin formatear de ChatGPT o herramientas similares serán penalizados (e.g: "Inserta tu modelo acá", etc.)**

<center>
<img src="https://media1.giphy.com/media/ZkIUY6LZJMwrSMQMWu/giphy.gif?cid=6c09b952msc755426bpsadn4sysofcpqczczi7x1pghd41sw&ep=v1_internal_gif_by_id&rid=giphy.gif&ct=v" width="400" height="300">

# 📬 Entrega Parcial 3 (30% del Proyecto)

### 📪 Fecha de Entrega: 

Esta entrega cuenta con 2 partes:

- **Predicciones**: 1 de Diciembre, 2 de Diciembre, 3 de Diciembre, 4 de Diciembre
- **Informe:** 8 de Diciembre.

## 📖 Enunciado

Después de haber superado con éxito la implementación de sus flujos de trabajo con `Airflow`, el equipo **Deep Drinkers 🤖** ha demostrado que no solo sabe construir modelos, sino también integrarlos en pipelines reales listos para producción.

El equipo técnico de **SodAI Drinks 🥤** ha quedado tan satisfecho con la automatización de sus procesos que ahora les ha encomendado una nueva, y final, misión:  
- 📊 **Evaluar la calidad real de sus modelos en un entorno más desafiante** 
- 🧠 **Comunicar los hallazgos de forma clara y profesional frente a una comisión**.

<center>
<img src="https://i.giphy.com/btbUGSHh3f6eBjbDfh.webp" width="350">

## 📌 Predicciones
<center>
<img src="https://i.giphy.com/NTMxntb8rMzmbd1x97.webp" width="500" height="300">
</center>

Su *pipeline* automatizado debe demostrar que puede manejar datos reales en producción. **SodAI Drinks** 🥤 liberará *batches* de datos en fechas diferentes para evaluar si su sistema se adapta correctamente, los cuales simularán la llegada de información nueva (cada batch es una semana).

Lo que debe funcionar automáticamente:
- **Ejecución Automatizada**: Su DAG de `Airflow` debe ser capaz de procesar cada *batch* de datos de manera automática cuando esté disponible.
- **Monitoreo Continuo**: El *pipeline* debe evaluar la calidad de los datos entrantes y detectar posibles desviaciones respecto al conjunto original.
- **Decisión de Reentrenamiento**: Basándose en los análisis de *data drift* y métricas de rendimiento, el sistema debe determinar automáticamente si es necesario reentrenar el modelo.
- **Tracking Completo**: Todas las ejecuciones, métricas y decisiones deben quedar registradas en `MLFlow` para posterior análisis.
- **Generación de Predicciones**: Para cada *batch* procesado, el sistema debe generar las predicciones correspondientes y almacenarlas de manera organizada.

**IMPORTANTE: Es imperativo que guarden los resultados de su pipeline (métricas, tracking, predicciones, etc) para su análisis en la siguiente sección.**

### 📌Entregable: Competencia en CodaLab

<center>
<img src="https://i.giphy.com/NomCzPIGoXs3EIq77v.webp" width="300" height="300">
</center>

Como parte de esta entrega final, el equipo debe utilizar su pipeline entrenado para **generar predicciones en los nuevos conjuntos de datos mencionados anteriormente**.

Estas predicciones deben:

- Ser generadas directamente desde el *pipeline* previamente desarrollado.  
- Guardarse en archivos `.csv` siguiendo el formato requerido.  
- Subirse a la plataforma **CodaLab**, donde se realizará la evaluación final.

En CodaLab podrán:

- Ver el rendimiento de su modelo frente a los de otros equipos.  
- Obtener una puntuación basada en la métrica definida del proyecto.  

Cada set de predicciones debe ser publicado en CodaLab en las siguientes fechas:
- **Predicciones 1 📅** : 1 de Diciembre (Fecha de predicción: 01/01/25 - 05/01/25)
    - Note que para este set de predicciones, sólo tendrán acceso a los datos publicados en la Entrega 1.
- **Predicciones 2 📅** : 2 de Diciembre (Fecha de predicción: 06/01/25 - 12/01/25)
- **Predicciones 3 📅** : 3 de Diciembre (Fecha de predicción: 13/01/25 - 19/01/25)
- **Predicciones 4 📅** : 4 de Diciembre (Fecha de predicción: 20/01/25 - 26/01/25)

Para simular la llegada de nuevos datos, se publicarán los siguientes conjuntos de datos:
- **Batch 1 📅** : 2 de Diciembre (Con datos realizados del período 01/01/25 - 05/01/25)
- **Batch 2 📅** : 3 de Diciembre (Con datos realizados del período 06/01/25 - 12/01/25)
- **Batch 3 📅** : 4 de Diciembre (Con datos realizados del período 13/01/25 - 19/01/25)
- **Batch 4 📅** : 5 de Diciembre (Con datos realizados del período 20/01/25 - 26/01/25)
    - Note como este conjunto de datos se publica **después** de la competencia, por lo que sólo les servirá para la última evaluación requerida en el informe.

**IMPORTANTE:** Subir los resultados a tiempo en las tres fechas es **<u>OBLIGATORIO</u>** para la evaluación del desempeño final del equipo. **Por cada fecha en la que no se suban predicciones, se aplicará un descuento de 0.75 puntos (75 décimas) sobre la nota de la Entrega 3.**

### 🎁 Bonus [0.5 puntos]

Como incentivo adicional, se premiará a los **3 equipos con mejor performance en la métrica F1** con **0.5 puntos de puntaje adicional** sobre la nota de la Entrega 3.

## 📌 Informe: Performance del modelo [6.0 puntos]

En esta sección se espera que el equipo analice de manera retrospectiva el performance de su modelo y saque conclusiones en función de sus resultados. 

Para esto, tendrán que incurrir en 3 tipos de análisis:

- **Individual:** Deben evaluar el performance de su modelo tomando cada semana de forma aislada.

- **Comparativo:** Deben evaluar el performance de su modelo *a través* de las semanas, comparando el desempeño entre las semanas e identificando posibles tendencias.
    - Para esta parte se espera que generen gráficos de tendencia y tablas comparativas para apoyar su análisis.

- **Conclusiones y Aprendizajes:** Deben escribir sus principales conclusiones y aprendizajes de este proyecto. 

A lo largo de esta sección, se espera que respondan preguntas como:

1. ¿Cómo variaron sus métricas a lo largo de los distintos conjuntos de datos? 
2. ¿En qué momento el modelo tuvo su peor desempeño y por qué?
3. ¿Detectaron algún cambio significativo (drift) en la distribución de los datos? ¿Cómo lo identificaron?  
4. ¿Tuvieron que reentrenar su modelo con los nuevos datos? ¿Porqué? ¿Ayudó esto al performance de su modelo?
4. ¿Qué decisión técnica (modelo, métrica, imputación, etc.) tuvo más impacto en los resultados?  
5. ¿Qué hiperparámetro fue el más importante para su modelo? 
5. ¿Qué variable fue más influyente en las predicciones? ¿Cómo lo interpretan? ¿Cómo cambió su importancia con respecto a las otras variables a lo largo de los batch de datos?
6. ¿Qué aprendieron sobre el negocio a partir de los resultados del modelo?
7. ¿Qué limitaciones detectaron en su modelo o en los datos?  

**IMPORTANTE: Se espera que en sus respuestas hagan referencia a los artefactos (métricas, hiperparámetros, gráficos de interpretabilidad, etc) que su pipeline genera.**

<center>
<img src="https://media1.tenor.com/m/jyQ3SPT1htEAAAAd/i-love-this-performance-even-more-simon-cowell.gif" width="300" height="300">
</center>

### 📌 Análisis individual [3.0 puntos]

In [1]:
## Importación de librerías
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

from pathlib import Path

In [2]:
##### Ruta(s) archivo(s)

# BATCH 0
BATCH_0 = "../entrega_3/RESULTADOS_AIRFLOW_MLFLOW/BATCH_0/MLFLOW/ARTIFACTS_BATCH_0/"

# BATCH 1
BATCH_1 = "../entrega_3/RESULTADOS_AIRFLOW_MLFLOW/BATCH_1/MLFLOW/ARTIFACTS_BATCH_1/"

# BATCH 2
BATCH_2  = "../entrega_3/RESULTADOS_AIRFLOW_MLFLOW/BATCH_2/MLFLOW/ARTIFACTS_BATCH_2/"

# BATCH 3
BATCH_3 = "../entrega_3/RESULTADOS_AIRFLOW_MLFLOW/BATCH_3/MLFLOW/ARTIFACTS_BATCH_3/"

# ULTIMO DATAFRAME
LAST_DATA = "../entrega_2/airflow/data/" 
df_last = pd.read_parquet(LAST_DATA+"df_final_latest.parquet")

In [8]:
df_last.head()

,customer_id,product_id,week_t,week_t_plus_1,semana,semana_siguiente_str,purchased_count,compra_o_no,y,customer_type,...,region_id,num_deliver_per_week,num_visit_per_week,brand,category,sub_category,segment,package,size,semana_num
0,123150,10652,2024-01-01,2024-01-08,2024-01,2024-02,0,0,0,ABARROTES,...,80,4,1,Brand 34,BEBIDAS CARBONATADAS,GASEOSAS,MEDIUM,LATA,0.25,202401
1,123150,10790,2024-01-01,2024-01-08,2024-01,2024-02,0,0,0,ABARROTES,...,80,4,1,Brand 1,BEBIDAS CARBONATADAS,GASEOSAS,PREMIUM,BOTELLA,0.33,202401
2,123150,10808,2024-01-01,2024-01-08,2024-01,2024-02,0,0,0,ABARROTES,...,80,4,1,Brand 35,BEBIDAS CARBONATADAS,GASEOSAS,MEDIUM,BOTELLA,0.66,202401
3,123150,11262,2024-01-01,2024-01-08,2024-01,2024-02,0,0,0,ABARROTES,...,80,4,1,Brand 24,BEBIDAS CARBONATADAS,GASEOSAS,LOW,LATA,0.25,202401
4,123150,11490,2024-01-01,2024-01-08,2024-01,2024-02,0,0,0,ABARROTES,...,80,4,1,Brand 26,BEBIDAS CARBONATADAS,GASEOSAS,HIGH,BOTELLA,0.33,202401

In [7]:
print("Dimensiones df_last: ", df_last.shape)

Dimensiones df_last:  (9717960, 23)

In [10]:
df_last[
    (df_last["week_t"] >= "2025-01-01") 
    & (df_last["week_t"] <= "2025-01-30")
]

,customer_id,product_id,week_t,week_t_plus_1,semana,semana_siguiente_str,purchased_count,compra_o_no,y,customer_type,...,region_id,num_deliver_per_week,num_visit_per_week,brand,category,sub_category,segment,package,size,semana_num
9197355,123150,10652,2025-01-06,2025-01-13,2025-02,2025-03,0,0,0,ABARROTES,...,80,4,1,Brand 34,BEBIDAS CARBONATADAS,GASEOSAS,MEDIUM,LATA,0.25,202502
9197356,123150,10790,2025-01-06,2025-01-13,2025-02,2025-03,0,0,0,ABARROTES,...,80,4,1,Brand 1,BEBIDAS CARBONATADAS,GASEOSAS,PREMIUM,BOTELLA,0.33,202502
9197357,123150,10808,2025-01-06,2025-01-13,2025-02,2025-03,0,0,0,ABARROTES,...,80,4,1,Brand 35,BEBIDAS CARBONATADAS,GASEOSAS,MEDIUM,BOTELLA,0.66,202502
9197358,123150,11262,2025-01-06,2025-01-13,2025-02,2025-03,0,0,0,ABARROTES,...,80,4,1,Brand 24,BEBIDAS CARBONATADAS,GASEOSAS,LOW,LATA,0.25,202502
9197359,123150,11490,2025-01-06,2025-01-13,2025-02,2025-03,0,0,0,ABARROTES,...,80,4,1,Brand 26,BEBIDAS CARBONATADAS,GASEOSAS,HIGH,BOTELLA,0.33,202502
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9717955,96444,63418,2025-01-20,2025-01-27,2025-04,2025-05,0,0,0,ABARROTES,...,80,3,1,Brand 35,BEBIDAS CARBONATADAS,GASEOSAS,MEDIUM,LATA,0.25,202504
9717956,96444,63508,2025-01-20,2025-01-27,2025-04,2025-05,0,0,0,ABARROTES,...,80,3,1,Brand 44,BEBIDAS CARBONATADAS,GASEOSAS,HIGH,BOTELLA,0.25,202504
9717957,96444,63510,2025-01-20,2025-01-27,2025-04,2025-05,0,0,0,ABARROTES,...,80,3,1,Brand 44,BEBIDAS CARBONATADAS,GASEOSAS,HIGH,LATA,0.25,202504
9717958,96444,63538,2025-01-20,2025-01-27,2025-04,2025-05,0,0,0,ABARROTES,...,80,3,1,Brand 31,BEBIDAS CARBONATADAS,GASEOSAS,PREMIUM,LATA,0.25,202504
9717959,96444,63540,2025-01-20,2025-01-27,2025-04,2025-05,0,0,0,ABARROTES,...,80,3,1,Brand 54,BEBIDAS CARBONATADAS,GASEOSAS,HIGH,BOTELLA,0.33,202504

#### 📌 Batch 1 (01/01/25 - 05/01/25) [0.75 puntos]

In [2]:
# En esta celda se debe importar el modelo del batch 1:
# Batch 1: Nuevos Datos recolectados desde 01-01-2025 a 05-01-2025
# Se debe evaluar el modelo en los conjuntos de val/testeo y obtener métricas.

######## CARGA DEL MODELO #######


######## EVALUACIÓN EN SOLO DATOS DEL BATCH 1

#### 📌 Batch 2 (06/01/25 - 12/01/25) [0.75 puntos]

In [ ]:
# código para evaluar el performance de su modelo

#### 📌 Batch 03 (13/01/25 - 19/01/25) [0.75 puntos]

In [1]:
# código para evaluar el performance de su modelo

#### 📌 Batch 04 (20/01/25 - 26/01/25) [0.75 puntos]

In [ ]:
# código para evaluar el performance de su modelo

### 📌 Análisis comparativo [2.0 puntos]

In [ ]:
# código para realizar análisis de resultados entre batchs

### 📌 Conclusiones y Aprendizajes [1.0 puntos]

> [Escriba aquí sus conclusiones y aprendizajes]

## 📁 Estructura de entrega

Se espera que su entrega cuente con la siguiente estructura de carpetas:

```bash
entrega_3/
│
├── informe.ipynb # Jupyter notebook con sus resultados
│
├── predictions/ # Carpeta con las predicciones para cada batch de datos
│
└── data/ # Carpeta con los datos realizados (lo que realmente ocurrió)
```

Mucho éxito!

<center>
<img src="https://gifdb.com/images/high/may-the-force-be-with-you-anakin-skywalker-n2g5o0pm4h6iylsx.gif" width="400" height="300">